version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

hooks:
  AfterInstall:
    - location: scripts/afterInstall.sh

  ApplicationStart:
    - location: scripts/applicationStart.sh
      timeout: 300

  AfterBlockTraffic:
    - location: scripts/afterBlockTraffic.sh
